name: Build, Push, Deploy to AWS

on:
  push:
    branches:
      - "*"

jobs:
  build-and-upload-to-ecr:
    runs-on: ubuntu-latest
    environment:
      name: prod  # Optional: Set an environment name for clarity

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Build the image
        run: |
          docker build -t ${{ secrets.AWS_ECR_IMAGE }} .

      - name: Push to ECR
        run: |
          docker push ${{ secrets.AWS_ECR_IMAGE }}

      - name: Install Docker on EC2 instance via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            if [ -x "$(command -v docker)" ]; then
              echo "Update docker"
            else
              echo "Install docker"
              sudo yum install docker -y
              sudo service docker start
              sudo usermod -a -G docker ${{ secrets.AWS_EC2_USERNAME }}
            fi
            docker stop $(docker ps -aqf "ancestor=${{ secrets.AWS_ECR_IMAGE }}")
            docker rm $(docker ps -aqf "ancestor=${{ secrets.AWS_ECR_IMAGE }}")
            docker pull ${{ secrets.AWS_ECR_IMAGE }}
            docker run -d -p 8000:8000 ${{ secrets.AWS_ECR_IMAGE }}
#      - name: Build image and upload to ECR
#        run: |
#          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 975695045761.dkr.ecr.eu-central-1.amazonaws.com
#          docker build -t first-node-docker .
#          docker tag first-node-docker:latest 975695045761.dkr.ecr.eu-central-1.amazonaws.com/first-node-docker:latest
#          docker push 975695045761.dkr.ecr.eu-central-1.amazonaws.com/first-node-docker:latest
#
#      - name: Prepare EC2 instance
#        run: |
#          docker stop 975695045761.dkr.ecr.eu-central-1.amazonaws.com/first-node-docker:latest
#
#      - name:
