name: Build, Push, Deploy to AWS

on:
  push:
    branches:
      - "*"

jobs:
  build-and-upload-to-ecr:
    runs-on: ubuntu-latest
    environment:
      name: prod  # Optional: Set an environment name for clarity

    steps:
      - uses: actions/checkout@v3

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-docker-login@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}

#      - name: Build image and upload to ECR
#        run: |
#          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 975695045761.dkr.ecr.eu-central-1.amazonaws.com
#          docker build -t first-node-docker .
#          docker tag first-node-docker:latest 975695045761.dkr.ecr.eu-central-1.amazonaws.com/first-node-docker:latest
#          docker push 975695045761.dkr.ecr.eu-central-1.amazonaws.com/first-node-docker:latest
#
#      - name: Prepare EC2 instance
#        run: |
#          docker stop 975695045761.dkr.ecr.eu-central-1.amazonaws.com/first-node-docker:latest
#
#      - name:
